#Uses csv generated by exporting active users from web portal.

function importUsers($pathToCsv) {
    $csv = Import-Csv $pathToCsv;
    return $csv;
}
function setPwToNeverExpire($users) {
    $users.UserPrincipalName | foreach { 
        Set-MsolUser -UserPrincipalName $_ -PasswordNeverExpires $true;
        if((Get-MsolUser -UserPrincipalName $users[0].UserPrincipalName | Select *).PasswordNeverExpires) {
            $res = "SUCCESS";
        } else {
            "FAILED"
        }        
        write-host "Set password for [ $_ ] to never expire... [ $res ]";
    }
    return $true;
}
function resetPws($users) {
    $creds = @();
    $users.UserPrincipalName | foreach { 
        if($_ -notcontains "aait") {
            $p = Set-MsolUserPassword -UserPrincipalName $_ -ForceChangePassword $false;
            $cred = @{"UserPrincipalName" = $_; "Password" = $p};
            $creds += New-Object PSObject -Property $cred;
            write-host "Reset password for [ $_ ]";
        } else {
            write-host "Skipping aait account: $_...";
        }
    }
    return $creds;
}
function exportCreds($exportPath, $creds) {
    write-host $creds;
    write-host $exportPath;
    $creds | export-csv -Path $exportPath -NoTypeInformation;
    return $true;
}

$scriptpath = $MyInvocation.MyCommand.Path;
$dir = Split-Path $scriptpath;
Write-host "Importing $dir\ConnectToO365.ps1...";
. $dir\ConnectToO365.ps1;

$pathToCsv = "$dir\users.csv";
$exportPath = "$dir\creds.csv";

$sesh = connectToO365;
$users = importUsers $pathToCsv;
setPwToNeverExpire $users;
$creds = resetPws $users;
exportCreds $exportPath $creds;
disconnectFromO365 $sesh;